### ISSUE TITLE
`npm audit fix -f` automatically moves this package to a broken version

### ISSUE THREAD

**Issue by kj800x** [timmson/node-lgtv-api#14]
Running `npm install node-lgtv-api` and then `npm audit fix -f` installs version `1.0.0` which has broken dependencies (is missing a dependency on `request`). It looks like version `1.0.0` was published first before the other versions, so is very out of date, but because of semver `npm audit` tries to update to it since it sees it as the latest version.

The best solution is probably to republish the current master as `1.0.1` so that semver treats that version as the latest.

**Comment by timmson** [comment]
Hi, @kj800x 

Thx for your issue. Try to upgrade to latest verstion - 0.9.6.
