### ISSUE TITLE
Migrate to Promises

### ISSUE THREAD

**Issue by timmson** [timmson/node-lgtv-api#8]

**Comment by chearmstrong** [comment]
Nice to here it's now planned. :)

**Comment by timmson** [comment]
@chearmstrong, you can checkout whole chain of calls there - https://github.com/timmson/mbt-platform.  
Actually I have possibility to control my TV via Telegram Bot. I think that is great:)

**Comment by chearmstrong** [comment]
Nice one mate. I'll update to this version and try it out. :)
